"""Alternative-futures (2x2) matrix generation.

Pick two key drivers; the tool crosses their poles into four quadrants and
emits a structured worksheet with seeded questions per quadrant. The
analyst's job is to name each quadrant-world and decide which succession
trigger classes it makes more or less likely.
"""

from __future__ import annotations

from dataclasses import dataclass

from . import data

QUADRANT_PROMPTS = [
    "Name this world in five words or fewer.",
    "Which succession trigger classes become MORE likely here, and why?",
    "Which become LESS likely?",
    "What is the first observable indicator that we are entering this world?",
    "Who gains and who loses among the key actors?",
]


@dataclass
class Quadrant:
    label: str          # e.g. "A1/B1"
    x_state: str
    y_state: str

    @property
    def heading(self) -> str:
        return f"{self.x_state} x {self.y_state}"


@dataclass
class FuturesMatrix:
    x_driver: dict
    y_driver: dict
    quadrants: list[Quadrant]


def build(x_driver_id: str, y_driver_id: str) -> FuturesMatrix:
    if x_driver_id == y_driver_id:
        raise ValueError("pick two different drivers for the matrix axes")
    x = data.get("drivers", x_driver_id)
    y = data.get("drivers", y_driver_id)
    quadrants = [
        Quadrant("Q1", x["pole_a"], y["pole_a"]),
        Quadrant("Q2", x["pole_b"], y["pole_a"]),
        Quadrant("Q3", x["pole_a"], y["pole_b"]),
        Quadrant("Q4", x["pole_b"], y["pole_b"]),
    ]
    return FuturesMatrix(x_driver=x, y_driver=y, quadrants=quadrants)


def render_markdown(matrix: FuturesMatrix) -> str:
    x, y = matrix.x_driver, matrix.y_driver
    lines = [
        f"# Alternative futures: {x['name']} x {y['name']}",
        "",
        f"- X axis — **{x['name']}**: {x['pole_a']} <-> {x['pole_b']}",
        f"  - {x['note']}",
        f"- Y axis — **{y['name']}**: {y['pole_a']} <-> {y['pole_b']}",
        f"  - {y['note']}",
        "",
        f"| | {x['pole_a']} | {x['pole_b']} |",
        "|---|---|---|",
        f"| **{y['pole_a']}** | Q1 | Q2 |",
        f"| **{y['pole_b']}** | Q3 | Q4 |",
        "",
    ]
    for q in matrix.quadrants:
        lines.append(f"## {q.label}: {q.heading}")
        lines.append("")
        for prompt in QUADRANT_PROMPTS:
            lines.append(f"- [ ] {prompt}")
        lines.append("")
    lines.append(
        "_Worksheet generated by xi-succession; fill in quadrant analysis, "
        "then promote the most decision-relevant quadrants into full "
        "scenarios (`xi-succession new`)._"
    )
    return "\n".join(lines) + "\n"
