"""Markdown report rendering for a ScenarioSet."""

from __future__ import annotations

from . import data, indicators, probability
from .models import ScenarioSet


def _fmt_prob(p: float | None) -> str:
    return f"{p:.0%}" if p is not None else "unassigned"


def render(scenario_set: ScenarioSet) -> str:
    lines = [
        f"# {scenario_set.title}",
        "",
        f"- **Analytic horizon:** {scenario_set.horizon}",
        f"- **Reference data as of:** {scenario_set.data_as_of}",
        f"- **Scenario set treated as exhaustive:** "
        f"{'yes' if scenario_set.exhaustive else 'no (working set)'}",
        "",
        "## Summary",
        "",
        "| Scenario | Trigger class | Probability |",
        "|---|---|---|",
    ]
    ordered = sorted(
        scenario_set.scenarios,
        key=lambda s: -(s.probability if s.probability is not None else -1),
    )
    for s in ordered:
        trig = data.get("triggers", s.trigger)["name"]
        lines.append(f"| {s.name} | {trig} | {_fmt_prob(s.probability)} |")
    lines.append("")

    findings = probability.coherence_findings(scenario_set)
    if findings:
        lines.append("## Coherence & assumptions flags")
        lines.append("")
        for f in findings:
            lines.append(f"- ⚠ {f}")
        lines.append("")

    for s in ordered:
        trig = data.get("triggers", s.trigger)
        lines.append(f"## {s.name} ({_fmt_prob(s.probability)})")
        lines.append("")
        lines.append(f"**Trigger class:** {trig['name']} — {trig['description']}")
        lines.append("")
        lines.append(s.summary)
        lines.append("")
        if s.pathway:
            lines.append("**Pathway:**")
            lines.append("")
            for i, step in enumerate(s.pathway, 1):
                lines.append(f"{i}. {step}")
            lines.append("")
        if s.key_actors:
            lines.append("**Key actors:**")
            lines.append("")
            for actor_id in s.key_actors:
                actor = data.get("actors", actor_id)
                positions = "; ".join(actor["positions"])
                lines.append(f"- **{actor['name']}** ({positions})")
            lines.append("")
        if s.indicators:
            lines.append("**Indicators to watch (strongest first):**")
            lines.append("")
            for entry in indicators.watchlist_for(s.indicators):
                lines.append(f"- (w{entry['weight']}) {entry['text']}")
            lines.append("")
        if s.assumptions:
            lines.append("**Key assumptions:**")
            lines.append("")
            lines.append("| Assumption | Confidence | Impact if wrong |")
            lines.append("|---|---|---|")
            for a in s.assumptions:
                marker = " ⚠" if a.load_bearing else ""
                lines.append(
                    f"| {a.text}{marker} | {a.confidence} | {a.impact_if_wrong} |"
                )
            lines.append("")
        if s.implications:
            lines.append("**Implications if realized:**")
            lines.append("")
            for imp in s.implications:
                lines.append(f"- {imp}")
            lines.append("")
        if s.analyst_notes:
            lines.append(f"_Analyst notes: {s.analyst_notes}_")
            lines.append("")

    # Consolidated watchlist across the whole set
    all_ind_ids = sorted({i for s in scenario_set.scenarios for i in s.indicators})
    if all_ind_ids:
        lines.append("## Consolidated indicator watchlist")
        lines.append("")
        lines.append("| Indicator | Weight | Signals toward | Collection note |")
        lines.append("|---|---|---|---|")
        for entry in indicators.watchlist_for(all_ind_ids):
            signals = ", ".join(entry["signals"])
            lines.append(
                f"| {entry['text']} | {entry['weight']} | {signals} | {entry['note']} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by the xi-succession toolkit. Scenario probabilities are "
        "structured analytic judgments, not forecasts with validated track "
        "records. Reference data is a snapshot (see date above) of an opaque, "
        "fast-moving system — verify before operational use._"
    )
    return "\n".join(lines) + "\n"
