// ============================================================
//  BROKER BATTLE — Insurance broker exam question bank
//  Pre-licensing fundamentals (general P&C + Life/Health +
//  law/ethics). State-specific numbers vary; these are the
//  broadly-tested concepts. Each item has a plain-English
//  explanation so a wrong answer still teaches something.
// ============================================================

export const CATEGORIES = {
  basics:   { name: "Principles",      color: "#3b82f6", blurb: "Core insurance concepts" },
  risk:     { name: "Risk",            color: "#8b5cf6", blurb: "Risk, peril, hazard" },
  contract: { name: "Contracts",       color: "#0ea5e9", blurb: "Policy & legal provisions" },
  life:     { name: "Life",            color: "#ec4899", blurb: "Life insurance" },
  health:   { name: "Health",          color: "#10b981", blurb: "Health & disability" },
  pc:       { name: "Property/Cas",    color: "#f59e0b", blurb: "Property & casualty" },
  law:      { name: "Law & Ethics",    color: "#ef4444", blurb: "Regulation & producer duties" },
};

// answer = index of correct choice (0-based)
export const QUESTIONS = [
  // ---------------- PRINCIPLES ----------------
  { cat: "basics", q: "What is 'insurable interest'?",
    choices: ["A financial stake such that a loss would cause genuine hardship", "Interest earned on policy reserves", "The insurer's profit margin", "A discount for loyal customers"],
    answer: 0, why: "Insurable interest means the policyowner would suffer a real financial loss if the insured event occurred. It must exist or the contract is a wager and is void." },
  { cat: "basics", q: "For PROPERTY insurance, when must insurable interest exist?",
    choices: ["Only when the policy is purchased", "At the time of the loss", "Only at policy renewal", "It is never required for property"],
    answer: 1, why: "Property insurable interest must exist at the time of loss (you must own/have a stake in the thing damaged). For LIFE insurance it must exist only at policy inception." },
  { cat: "basics", q: "The principle of INDEMNITY says an insured should be:",
    choices: ["Paid more than the loss to deter future claims", "Restored to roughly the same financial position as before the loss — no better", "Paid only if not at fault", "Reimbursed for emotional damages first"],
    answer: 1, why: "Indemnity restores you to your pre-loss financial condition. You shouldn't profit from a loss — that would create moral hazard." },
  { cat: "basics", q: "'Adverse selection' refers to the tendency of:",
    choices: ["Insurers to pick only healthy clients", "Higher-risk people to seek insurance more than lower-risk people", "Agents to select the cheapest carrier", "Regulators to favor large insurers"],
    answer: 1, why: "Those most likely to have a loss are most likely to want coverage. Underwriting and rating exist to counter adverse selection." },
  { cat: "basics", q: "The 'law of large numbers' lets insurers:",
    choices: ["Charge whatever they want", "Predict losses more accurately as the number of similar exposures grows", "Avoid paying small claims", "Guarantee no insured will ever have a loss"],
    answer: 1, why: "With a large pool of similar risks, actual losses come close to predicted losses, making rates calculable and reliable." },
  { cat: "basics", q: "Which is one of the elements of an INSURABLE risk?",
    choices: ["The loss must be catastrophic to the insurer", "The loss must be due to chance and definite/measurable", "The insured must be wealthy", "The peril must be illegal"],
    answer: 1, why: "Insurable losses are accidental (chance), definite in time/place/amount, measurable, and not catastrophic to the insurer. The pool must also be large and homogeneous." },
  { cat: "basics", q: "'Utmost good faith' (uberrimae fidei) in insurance means:",
    choices: ["The insurer must pay all claims without question", "Both parties rely on each other's honest, complete disclosure", "The agent works only for the insured", "Premiums can never increase"],
    answer: 1, why: "Insurance contracts assume both sides deal honestly and disclose material facts. Concealment or misrepresentation can void coverage." },
  { cat: "basics", q: "Reinsurance is best described as:",
    choices: ["Insurance an insured buys twice", "Insurance that an insurer buys to transfer part of its own risk", "A second policy on the same car", "Government-backed coverage"],
    answer: 1, why: "Reinsurance lets a primary (ceding) insurer share risk with a reinsurer, stabilizing results and increasing capacity." },

  // ---------------- RISK ----------------
  { cat: "risk", q: "A 'peril' is:",
    choices: ["The cause of a loss (e.g., fire, theft, windstorm)", "A condition that increases the chance of loss", "The dollar amount of a loss", "A type of insurance policy"],
    answer: 0, why: "A peril is the actual cause of loss. Fire, theft, and collision are perils. Don't confuse it with a hazard (which increases likelihood/severity)." },
  { cat: "risk", q: "A 'hazard' is:",
    choices: ["The cause of a loss", "A condition that increases the likelihood or severity of a loss", "An insurance company's reserve", "The premium charged"],
    answer: 1, why: "A hazard makes a peril more likely or more severe — e.g., oily rags (physical), smoking (lifestyle), or filing a fraudulent claim (moral)." },
  { cat: "risk", q: "Storing gasoline near a furnace is an example of a:",
    choices: ["Moral hazard", "Morale hazard", "Physical hazard", "Speculative risk"],
    answer: 2, why: "A physical hazard is a tangible condition of the property/person that increases risk. Moral = dishonesty; morale = carelessness/indifference." },
  { cat: "risk", q: "Leaving your car unlocked because 'insurance will cover it' is a:",
    choices: ["Physical hazard", "Morale hazard", "Moral hazard", "Pure risk"],
    answer: 1, why: "Morale hazard is indifference/carelessness arising because one has insurance. Moral hazard involves actual dishonesty (e.g., faking a theft)." },
  { cat: "risk", q: "Which type of risk is INSURABLE?",
    choices: ["Speculative risk (chance of gain or loss)", "Pure risk (chance of loss or no loss only)", "Market risk", "Entrepreneurial risk"],
    answer: 1, why: "Only pure risk — where the outcomes are loss or no loss — is insurable. Speculative risk includes a chance of gain (like gambling or investing) and is not." },
  { cat: "risk", q: "Which is a method of risk RETENTION?",
    choices: ["Buying an insurance policy", "Choosing a higher deductible / self-insuring", "Installing a sprinkler system", "Demolishing a hazardous building"],
    answer: 1, why: "Retention means keeping the financial responsibility for a risk — e.g., a deductible or self-insurance. Avoidance, reduction, and transfer (insurance) are the others." },
  { cat: "risk", q: "Installing smoke detectors and sprinklers is an example of risk:",
    choices: ["Avoidance", "Transfer", "Reduction", "Retention"],
    answer: 2, why: "Risk reduction (loss control) lowers the frequency or severity of loss. It doesn't eliminate the risk (avoidance) or shift it to an insurer (transfer)." },

  // ---------------- CONTRACTS ----------------
  { cat: "contract", q: "Which is NOT one of the four required elements of a valid contract?",
    choices: ["Offer and acceptance (agreement)", "Consideration", "Competent parties / legal capacity", "Notarization by a state official"],
    answer: 3, why: "The four elements are agreement (offer & acceptance), consideration, competent parties, and legal purpose. Notarization is not required." },
  { cat: "contract", q: "An insurance contract is 'unilateral,' meaning:",
    choices: ["Only one party makes a legally enforceable promise (the insurer)", "Both parties promise equally", "It can be canceled by anyone anytime", "It covers only one person"],
    answer: 0, why: "Only the insurer makes an enforceable promise (to pay covered claims). The insured isn't legally required to pay premiums — they just lose coverage if they don't." },
  { cat: "contract", q: "An insurance contract is a contract of 'adhesion' because:",
    choices: ["Premiums adhere to inflation", "It is written by the insurer and offered take-it-or-leave-it", "Both parties draft the terms together", "It sticks the insured with all liability"],
    answer: 1, why: "The insurer drafts the contract; the insured cannot negotiate terms. Because of this, ambiguities are generally construed against the insurer (in favor of the insured)." },
  { cat: "contract", q: "'Aleatory' means an insurance contract:",
    choices: ["Has equal value exchanged by both sides", "Involves an exchange of unequal amounts depending on chance", "Must be in writing", "Renews automatically"],
    answer: 1, why: "Aleatory contracts depend on an uncertain event: a small premium may yield a large claim payment, or no payment at all. Values exchanged are unequal by nature." },
  { cat: "contract", q: "A 'material misrepresentation' on an application is one that:",
    choices: ["Is a minor typo in the address", "Would have changed the insurer's decision to issue or rate the policy", "Concerns the agent's commission", "Appears only in the declarations page"],
    answer: 1, why: "A misrepresentation is material if the truth would have affected the underwriting decision. Material misreps can void the policy." },
  { cat: "contract", q: "'Concealment' is:",
    choices: ["Failing to disclose a known material fact", "Stating a deliberate falsehood", "A promise about the future", "An endorsement to a policy"],
    answer: 0, why: "Concealment is the intentional withholding of a known material fact. Misrepresentation is an affirmative false statement; both can void coverage." },
  { cat: "contract", q: "A 'warranty' in an insurance contract is:",
    choices: ["An opinion or belief", "A statement guaranteed to be true, becoming part of the contract", "A type of deductible", "The agent's promise of good service"],
    answer: 1, why: "A warranty is guaranteed true and part of the contract; breaching it can void coverage. A representation is only believed true to the best of the applicant's knowledge." },
  { cat: "contract", q: "The 'entire contract' provision means:",
    choices: ["The policy plus the attached application form the whole agreement", "Only the declarations page matters", "Oral statements override the written policy", "The insurer can add terms later without notice"],
    answer: 0, why: "The policy and attached application together constitute the entire contract; nothing outside it (like prior oral statements) can be used to alter it." },
  { cat: "contract", q: "An 'endorsement' or 'rider' is:",
    choices: ["A cancellation notice", "An amendment that adds, removes, or changes policy coverage", "The signature page", "A claims form"],
    answer: 1, why: "Endorsements (P&C term) and riders (life/health term) modify the base policy. They take precedence over conflicting policy language." },
  { cat: "contract", q: "'Estoppel' prevents a party from:",
    choices: ["Renewing a policy", "Asserting a right they previously waived or led the other to rely on giving up", "Filing any claim", "Changing beneficiaries"],
    answer: 1, why: "Waiver is the voluntary giving up of a known right; estoppel then bars you from reasserting that right when the other party relied on the waiver." },

  // ---------------- LIFE ----------------
  { cat: "life", q: "Which life policy provides lifetime protection and builds cash value?",
    choices: ["Term life", "Whole life", "Accidental death only", "Credit life"],
    answer: 1, why: "Whole life is permanent: level premiums, lifetime coverage, and guaranteed cash value. Term covers a set period with no cash value." },
  { cat: "life", q: "Term life insurance is best characterized by:",
    choices: ["Cash value accumulation", "Coverage for a specified period with no cash value", "Guaranteed dividends", "Premiums that always decrease"],
    answer: 1, why: "Term provides pure death-benefit protection for a set term (e.g., 10/20 years) and builds no cash value — generally the lowest initial cost." },
  { cat: "life", q: "The 'incontestability' clause means after a set period (usually 2 years) the insurer:",
    choices: ["Can raise premiums freely", "Cannot contest the policy for misstatements except fraud", "Must double the death benefit", "Can cancel for any reason"],
    answer: 1, why: "After the contestable period (commonly 2 years), the insurer generally cannot deny a claim based on application misstatements (fraud may be an exception by state)." },
  { cat: "life", q: "A life insurance 'free look' period lets the owner:",
    choices: ["Borrow against the policy immediately", "Return the policy for a full refund within a set number of days", "Skip the first premium", "Change insurers for free annually"],
    answer: 1, why: "The free-look (typically 10–30 days) lets a new policyowner return the policy for a full premium refund if unsatisfied — a key consumer protection." },
  { cat: "life", q: "The 'grace period' in a life policy is the time:",
    choices: ["Before coverage begins", "After a missed premium during which the policy stays in force", "To name a beneficiary", "To complete the application"],
    answer: 1, why: "The grace period (often 30/31 days) keeps coverage in force after a missed premium. If the insured dies during it, the benefit is paid minus the owed premium." },
  { cat: "life", q: "A 'revocable' beneficiary designation means the policyowner:",
    choices: ["Can never change the beneficiary", "Can change the beneficiary at any time without consent", "Needs the beneficiary's permission to make changes", "Must name the estate"],
    answer: 1, why: "A revocable beneficiary can be changed anytime by the owner. An irrevocable beneficiary must consent to changes affecting their interest." },
  { cat: "life", q: "Universal life insurance is known for its:",
    choices: ["Fixed, unchangeable premium and benefit", "Flexible premiums and adjustable death benefit", "Lack of any cash value", "Coverage only until age 30"],
    answer: 1, why: "Universal life is flexible-premium permanent insurance: within limits the owner can adjust premiums and the death benefit, with cash value tied to a credited interest rate." },
  { cat: "life", q: "The 'nonforfeiture' options in whole life protect the:",
    choices: ["Insurer's profit", "Cash value the policyowner has built if the policy lapses or is surrendered", "Agent's commission", "Beneficiary's tax status"],
    answer: 1, why: "Nonforfeiture options (cash surrender, reduced paid-up, extended term) guarantee the owner doesn't forfeit accumulated cash value." },

  // ---------------- HEALTH ----------------
  { cat: "health", q: "A health insurance 'deductible' is:",
    choices: ["The monthly premium", "The amount the insured pays out of pocket before the insurer pays", "The insurer's maximum payout", "A fixed fee per office visit"],
    answer: 1, why: "The deductible is what you pay before benefits kick in. A copay is a flat per-service fee; coinsurance is a percentage split after the deductible." },
  { cat: "health", q: "'Coinsurance' (e.g., 80/20) means:",
    choices: ["The insurer pays 20%", "After the deductible, insurer and insured split costs (e.g., 80% / 20%)", "A flat $20 copay", "Two insurers share one policy"],
    answer: 1, why: "Coinsurance is the percentage split of covered costs after the deductible — in 80/20, the plan pays 80% and you pay 20% up to the out-of-pocket max." },
  { cat: "health", q: "An 'elimination period' in a disability income policy is:",
    choices: ["The waiting period before benefits begin after disability", "The maximum benefit period", "The time to file a claim", "The free-look window"],
    answer: 0, why: "The elimination (waiting) period is a deductible measured in time — benefits start only after the insured has been disabled for that number of days." },
  { cat: "health", q: "In a Health Maintenance Organization (HMO), care is usually coordinated by:",
    choices: ["Any specialist the patient chooses", "A primary care physician (PCP) who provides referrals", "The insurance agent", "The state insurance department"],
    answer: 1, why: "HMOs emphasize a PCP gatekeeper and in-network care with referrals for specialists. PPOs offer more freedom to see out-of-network providers at higher cost." },
  { cat: "health", q: "A 'pre-existing condition' is generally:",
    choices: ["Any condition that develops after the policy starts", "A condition for which the insured received care before the policy's effective date", "A condition the agent recommends covering", "Only conditions requiring surgery"],
    answer: 1, why: "A pre-existing condition existed (or was treated) before coverage began. Modern law (ACA) limits exclusions, but the concept is heavily tested." },
  { cat: "health", q: "'Guaranteed renewable' health coverage means the insurer:",
    choices: ["Can cancel anytime", "Must renew if premiums are paid, but may raise rates by class", "Can never change premiums", "Renews only with a new medical exam"],
    answer: 1, why: "Guaranteed renewable policies must be renewed as long as premiums are paid; the insurer may raise rates only for an entire class, not an individual." },
  { cat: "health", q: "Long-term care (LTC) insurance primarily covers:",
    choices: ["Hospital surgery costs", "Custodial/assisted care for those who can't perform activities of daily living", "Prescription drugs only", "Dental and vision"],
    answer: 1, why: "LTC pays for extended custodial care (help with activities of daily living like bathing, dressing, eating) in facilities or at home — costs medical insurance won't cover." },

  // ---------------- PROPERTY & CASUALTY ----------------
  { cat: "pc", q: "A homeowners policy's LIABILITY coverage pays for:",
    choices: ["Damage to the insured's own home", "Bodily injury or property damage the insured is legally responsible for to others", "The insured's medical checkups", "Auto collision"],
    answer: 1, why: "Liability (Coverage E in HO policies) covers third-party bodily injury and property damage for which the insured is legally liable, plus defense costs." },
  { cat: "pc", q: "'Subrogation' allows the insurer to:",
    choices: ["Cancel the policy after a claim", "Recover its payout from the at-fault third party after paying the insured", "Increase the deductible retroactively", "Deny all future claims"],
    answer: 1, why: "After indemnifying its insured, the insurer 'steps into the insured's shoes' to recover from the responsible party — preventing double recovery and supporting indemnity." },
  { cat: "pc", q: "A 'coinsurance clause' in property insurance penalizes insureds who:",
    choices: ["File too many claims", "Carry less than a required percentage (e.g., 80%) of the property's value", "Pay premiums late", "Add endorsements"],
    answer: 1, why: "If you insure below the required percentage (commonly 80%) of replacement value, the coinsurance penalty reduces partial-loss payments proportionally." },
  { cat: "pc", q: "'Actual Cash Value' (ACV) is:",
    choices: ["Replacement cost with no deductions", "Replacement cost minus depreciation", "The original purchase price", "The amount of the premium"],
    answer: 1, why: "ACV = replacement cost − depreciation. Replacement cost coverage pays to replace with new property of like kind without the depreciation deduction." },
  { cat: "pc", q: "In auto insurance, 'comprehensive' (other-than-collision) coverage pays for:",
    choices: ["Damage from a collision with another car", "Theft, fire, hail, vandalism, and animal strikes", "Your bodily injury liability to others", "Legal defense costs only"],
    answer: 1, why: "Comprehensive covers non-collision losses — theft, fire, falling objects, vandalism, glass, and hitting an animal. Collision covers impact with a vehicle/object." },
  { cat: "pc", q: "'Uninsured motorist' coverage protects you when:",
    choices: ["Your own car needs repairs from wear", "An at-fault driver has no liability insurance", "You forget to pay your premium", "You drive someone else's insured car"],
    answer: 1, why: "UM coverage pays for your injuries (and sometimes property) when the at-fault driver has no insurance. Underinsured (UIM) applies when their limits are too low." },
  { cat: "pc", q: "A standard homeowners policy typically EXCLUDES:",
    choices: ["Fire damage", "Flood and earthquake", "Wind damage", "Theft of personal property"],
    answer: 1, why: "Flood and earthquake are standard exclusions — they require separate policies/endorsements (e.g., NFIP flood insurance). Fire, wind, and theft are covered perils." },
  { cat: "pc", q: "The 'declarations page' of a policy shows:",
    choices: ["The insurer's investment portfolio", "Who/what is insured, coverage limits, deductibles, and the premium", "Every exclusion in full legal text", "The agent's licensing history"],
    answer: 1, why: "The 'dec page' summarizes the specifics: named insured, property/vehicle, coverage limits, deductibles, policy period, and premium." },

  // ---------------- LAW & ETHICS ----------------
  { cat: "law", q: "An insurance producer (agent/broker) generally owes the insurer a duty of:",
    choices: ["Adverse selection", "Fiduciary care — handling premiums and information in good faith", "Speculation", "Subrogation"],
    answer: 1, why: "Producers hold a fiduciary duty: they handle others' money (premiums) and trust, and must act in good faith, keeping funds separate and remitting them properly." },
  { cat: "law", q: "Commingling is the prohibited act of:",
    choices: ["Selling two policies at once", "Mixing client/premium funds with the producer's personal funds", "Comparing carriers for a client", "Replacing an old policy"],
    answer: 1, why: "Commingling — mixing fiduciary/premium money with personal or business operating funds — is a serious violation that can cost a producer their license." },
  { cat: "law", q: "'Twisting' is an unfair trade practice that involves:",
    choices: ["Misrepresenting facts to induce a client to drop one policy for another", "Bundling home and auto", "Raising rates on a class", "Paying a referral fee to a licensed agent"],
    answer: 0, why: "Twisting uses misrepresentation/incomplete comparisons to convince a policyholder to replace coverage to the client's detriment. It is illegal." },
  { cat: "law", q: "'Rebating' generally means:",
    choices: ["Refunding an overpayment of premium", "Giving a client something of value (not in the policy) as an inducement to buy", "Lowering a deductible", "Returning unearned commission to the insurer"],
    answer: 1, why: "Rebating offers an inducement (cash, gifts, special favors) outside the policy terms to make a sale. It's prohibited in most states (a few now allow limited value)." },
  { cat: "law", q: "'Churning' differs from twisting because the replacement is:",
    choices: ["Between two different insurers", "Within policies of the SAME insurer using built-up values", "Always beneficial to the client", "Required by state law"],
    answer: 1, why: "Churning replaces a policy with a new one from the same insurer (often draining cash value) to generate commissions. Twisting involves a different insurer." },
  { cat: "law", q: "An agent who has authority the insurer hasn't expressly granted, but a reasonable client would assume exists, is acting under:",
    choices: ["Express authority", "Implied authority", "Apparent (ostensible) authority", "No authority"],
    answer: 2, why: "Apparent authority arises from the insurer's conduct leading a third party to reasonably believe the agent is authorized. Express = explicitly granted; implied = needed to carry out express duties." },
  { cat: "law", q: "Most states require a producer to remit collected premiums and keep them in:",
    choices: ["A personal checking account", "A separate trust/fiduciary account", "Cash in the office safe", "The client's own account"],
    answer: 1, why: "Premiums collected on the insurer's behalf are trust funds and must be held separately (a fiduciary/trust account) and remitted — never used personally." },
  { cat: "law", q: "A 'binder' is:",
    choices: ["A permanent policy document", "Temporary proof of coverage until the formal policy is issued", "A cancellation notice", "A claims settlement"],
    answer: 1, why: "A binder provides immediate, temporary coverage (oral or written) while the insurer completes underwriting and issues the actual policy." },
  { cat: "law", q: "The main purpose of a state insurance department / Commissioner is to:",
    choices: ["Maximize insurer profits", "Protect the public by regulating insurers and producers and enforcing the insurance code", "Set national tax policy", "Sell policies directly to consumers"],
    answer: 1, why: "State regulators license producers/insurers, ensure solvency, approve rates/forms, investigate complaints, and enforce consumer protections." },
  { cat: "law", q: "'Fiduciary responsibility' for premiums means a producer must:",
    choices: ["Invest premiums in stocks", "Hold and account for those funds in trust for the insurer/insured", "Keep premiums as a bonus", "Delay remitting to earn interest"],
    answer: 1, why: "The producer holds premium money in trust and must account for and remit it. Misusing these funds breaches fiduciary duty and the insurance code." },
];
