const E=[
["fri","6:00 PM","Ends 7:30 PM","K-Pop Dance + Random Play Dance","Greeley Square Park · Broadway at 32nd–33rd","Free K-pop dance lesson, then an open Random Play Dance.",["Free","Core","Movement"],"20–25 min","Drop-in","https://34thstreet.org/calendar/event/k-pop-dance","Greeley Square Park, New York, NY",false],
["fri","6:00 PM","Evening set","Strutman Lane","Times Square · Broadway at 46th Street","Eight-piece funk-pop band with horns and singalongs in the Broadway plaza.",["Free","Core by transit","Live music"],"15–20 min","Loud, crowded","https://www.timessquarenyc.org/events/tsqlive-26-friday-7-10","Times Square Broadway Plaza 46th Street, New York, NY",false],
["fri","6:00 PM","Family program","Deep Sea Costume Workshop + Dance Party","Lincoln Center · The Dance Floor","Make an undersea costume, then dance outdoors with DJ Miho Hatori.",["Free","Best for kids","Stretch"],"30–35 min","Roomy","https://www.lincolncenter.org/series/summer-for-the-city/create-athon-deep-sea-costume-workshop","Lincoln Center The Dance Floor, New York, NY",false],
["fri","6:30 PM","Ends 8:00 PM","Jazz on the Beach","Gansevoort Peninsula · Hudson River Park","Dance class, then Sonido Costeño’s salsa set and a waterfront sunset.",["Free","Best bet","Music + sand"],"20–25 min","Easy pick","https://hudsonriverpark.org/visit/events/event/west-side-fest-jazz-on-the-beach-july-10-2026/","Gansevoort Peninsula, New York, NY",false],
["fri","7:00 PM","Ends 8:30 PM","Avery Wilson · Carnegie Hall Citywide","Bryant Park Lawn","Open-air show tunes, R&B and anthems. Bring a picnic; some blankets on loan.",["Free","Core by transit","Picnic"],"15–20 min","Lawn picnic","https://bryantpark.org/calendar/event/aisha-jackson/2026-07-10","Bryant Park Lawn, New York, NY",false],
["sat","10:00 AM","Guided walk","Hudson River Park Nature Walk","Pier 45 · Christopher Street","Guided treasure hunt for birds, butterflies, bugs and native plants.",["Free","Registration encouraged","Nature"],"20–25 min","Keep quiet","https://hudsonriverpark.org/visit/events/event/nature-walks-july-11-2026/","Pier 45 Hudson River Park, New York, NY",false],
["sat","11:00 AM","Drop in until 6:00 PM","Summer Goals Open Streets","Little West 12th Street + West 13th Street","Car-free streets: clay, seed bombs, microgreens, crafts and juggling.",["Free","Best bet","All ages"],"20–25 min","Flexible","https://meatpacking-district.com/summer-goals-july-11","Little West 12th Street and West 13th Street, New York, NY",false],
["sat","3:00 PM","Guided stroll","Shoreline Stroll","Gansevoort Peninsula · Hudson River Park","Guided walk past shoreline, salt marsh, tide pools and pine grove.",["Free","Space limited","Nature"],"20–25 min","Sand after","https://hudsonriverpark.org/visit/events/event/west-side-fest-shoreline-strolls-july-11-2026/","Gansevoort Peninsula, New York, NY",false],
["sat","3:00 PM","Runs to 10:00 PM","From Stoops to Stadiums","American Museum of Natural History · West 79th Street","Outdoor block party: soccer, Double Dutch, chess, then salsa at sunset.",["Free","Stretch","Block party"],"35–45 min","Long trip","https://www.amnh.org/calendar/stoops-to-stadium","American Museum of Natural History West 79th Street, New York, NY",false],
["sat","5:00 PM","Ends about 7:00 PM","Norway v England — outdoor World Cup watch party","Pier 86 at the Intrepid · West 46th Street","Free quarter-final on big screens by the Hudson; food for sale. Arrive ~4 PM.",["Free","Featured","Multiple screens"],"30–40 min","Loud, exposed","https://intrepidmuseum.org/events/world-cup-watch-party","Intrepid Museum Pier 86, New York, NY",false],
["sat","8:20 PM","Full-sun alignment","Manhattanhenge","East 23rd Street · face west","The setting sun aligns with the street grid; view from 23rd Street.",["Free","Closest","Sunset"],"8–12 min","Late","https://www.amnh.org/research/hayden-planetarium/manhattanhenge","East 23rd Street and Broadway, New York, NY",false],
["sun","11:00 AM","Drop in until 6:00 PM","Summer Goals Open Streets","Little West 12th Street + West 13th Street","Sunday adds sun-print postcards, clay, sachets, crafts and jazz 3–6 PM.",["Free","All ages","Jazz at 3"],"20–25 min","Crafts, jazz","https://meatpacking-district.com/summer-goals-july-12","Little West 12th Street and West 13th Street, New York, NY",false],
["sun","11:00 AM","Sold out","A Myriad of Mandalas","Little Island","Family mandala art workshop, ages 3+. Advance spots sold out.",["Sold out","Ages 3+","Art"],"20–25 min","Backup only","https://littleisland.org/event/west-side-fest-a-myriad-of-mandalas/","Little Island, New York, NY",true],
["sun","12:00 PM","Runs to 5:00 PM","Carnaval Cubano Parade","Madison Avenue · East 38th to East 27th","Lively parade heading south on Madison; watch near East 27th.",["Free","Closest","Parade"],"10–15 min","Easy, loud","https://www.nyc.gov/html/dot/html/motorist/wkndtraf.shtml","Madison Avenue and East 27th Street, New York, NY",false],
["sun","1:00 PM","Ends 4:00 PM","Making Moves: Community Art Party","High Line · 14th Street Passage","Kid-focused community art and dance party at West Side Fest.",["Free","Best for kids","Art + dance"],"20–25 min","Kid pick","https://www.nycgovparks.org/parks/the-high-line/events/2026/07/12/making-moves-community-art-party-at-west-side-fest","High Line 14th Street Passage, New York, NY",false],
["sun","8:21 PM","Half-sun alignment","Manhattanhenge · second chance","East 23rd Street · face west","Half-sun grid alignment; the weekend’s last sunset spectacle.",["Free","Closest","Sunset"],"8–12 min","Late add-on","https://www.amnh.org/research/hayden-planetarium/manhattanhenge","East 23rd Street and Broadway, New York, NY",false]
],O="112 East 19th Street, New York, NY",M={fri:["Friday · July 10","After 5:30 PM","Nearby evening music, dance and picnics."],sat:["Saturday · July 11","All day · through 8:20 PM","Wider trips included. Football at 5 PM."],sun:["Sunday · July 12","11 AM · through 8:21 PM","Parade, family art, jazz and a sunset finale."]};const x=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),map=d=>'https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',origin:O,destination:d});function card(e){let[d,t,u,n,p,q,g,r,f,o,z,s]=e;return `<article class="card${s?' sold':''}"><div class="time">${x(t)}<small>${x(u)}</small></div><div class="body"><div class="badges">${g.map(a=>`<span>${x(a)}</span>`).join('')}</div><h3>${x(n)}</h3><b class="place">${x(p)}</b><p>${x(q)}</p><dl><div><dt>Travel</dt><dd>${x(r)}</dd></div><div><dt>Rayray</dt><dd>${x(f)}</dd></div></dl><div class="actions"><a class="primary" href="${x(o)}" target="_blank" rel="noopener">Official details</a><a href="${x(map(z))}" target="_blank" rel="noopener">Directions</a></div></div></article>`}document.getElementById('days').innerHTML=['fri','sat','sun'].map(d=>{let m=M[d];return `<section id="${d}" class="day"><div class="dayhead"><div><p class="kicker">${m[1]}</p><h2>${m[0]}</h2></div><p>${m[2]}</p></div><div class="grid">${E.filter(e=>e[0]===d).map(card).join('')}</div></section>`}).join('');const B=[...document.querySelectorAll('[data-filter]')],S=[...document.querySelectorAll('.day')];B.forEach(b=>b.onclick=()=>{B.forEach(a=>a.classList.toggle('active',a===b));let f=b.dataset.filter;S.forEach(a=>a.classList.toggle('hide',f!=='all'&&a.id!==f));if(f!=='all')document.getElementById(f).scrollIntoView({behavior:'smooth'})});
