const HOME='Union Square, New York, NY';
const events=[
 {day:'fri',time:'6:00 PM',end:'7:30 PM',title:'K-Pop Dance + Random Play Dance',place:'Greeley Square Park',addr:'Greeley Square Park, New York, NY',type:'Dance',tags:['Free','Outdoor','Wiggle-friendly'],desc:'A choreography lesson followed by participatory Random Play Dance—excellent for a toddler who wants to bounce instead of sit.',travel:'About 15–25 minutes from Union Square by subway/cab.',toddler:'Stand at the edge, dance for 20 minutes, leave happy.',url:'https://34thstreet.org/calendar/event/k-pop-dance'},
 {day:'fri',time:'6:30 PM',end:'8:00 PM',title:'Jazz on the Beach',place:'Gansevoort Peninsula',addr:'Gansevoort Peninsula, New York, NY',type:'Music',tags:['Free','Outdoor','Best bet'],desc:'Hudson River Park hosts Latin/salsa music and open dancing by the sand and water.',travel:'Around 20–30 minutes by transit/cab.',toddler:'Sand + music + sunset makes this the easiest Friday win.',url:'https://hudsonriverpark.org/visit/events/event/west-side-fest-jazz-on-the-beach-july-10-2026/'},
 {day:'fri',time:'7:00 PM',end:'Evening',title:'Avery Wilson · Carnegie Hall Citywide',place:'Bryant Park Lawn',addr:'Bryant Park, New York, NY',type:'Concert',tags:['Free','Outdoor','Picnic'],desc:'A big-lawn outdoor performance in Bryant Park, ideal for listening without requiring perfect toddler attention.',travel:'About 15–20 minutes by subway/cab.',toddler:'Bring snacks and a blanket; exit paths are easy.',url:'https://bryantpark.org/activities/picnic-performances'},
 {day:'sat',time:'11:00 AM',end:'6:00 PM',title:'Summer Goals Open Streets',place:'Meatpacking District',addr:'Little West 12th Street and West 13th Street, New York, NY',type:'Making',tags:['Free','Outdoor','Drop-in'],desc:'Car-free streets with clay, seed bombs, reading-and-craft tables, movement and juggling-style activities.',travel:'About 20–30 minutes by transit/cab.',toddler:'Most flexible Saturday option: snack, craft, wander, repeat.',url:'https://meatpacking-district.com/summer-goals-july-11'},
 {day:'sat',time:'12:00 PM',end:'Workshop',title:'SAB Family-Friendly Ballet Workshop',place:'Lincoln Center Dance Floor',addr:'Lincoln Center, New York, NY',type:'Ballet',tags:['Free','Outdoor','Family'],desc:'School of American Ballet faculty and advanced students demonstrate how ballet students train.',travel:'About 25–35 minutes by transit/cab.',toddler:'Short, visual, and movement-focused; stay near the back for freedom.',url:'https://lincolncenter.org/series/summer-for-the-city/sab-family-friendly-ballet-workshop-525'},
 {day:'sat',time:'3:00 PM',end:'Stroll',title:'Shoreline Stroll',place:'Gansevoort Peninsula',addr:'Gansevoort Peninsula, New York, NY',type:'Nature',tags:['Free','Outdoor','Guided'],desc:'A guided look at the sandy shoreline, salt marsh, tide pools and pine grove before open waterfront play.',travel:'Around 20–30 minutes by transit/cab.',toddler:'Good if you want nature but still need a real happening.',url:'https://hudsonriverpark.org/visit/events/event/west-side-fest-shoreline-strolls-july-11-2026/'},
 {day:'sat',time:'6:00 PM',end:'Workshop',title:'Freestyle Workshop with Nick Seyda',place:'Lincoln Center Dance Floor',addr:'Lincoln Center, New York, NY',type:'Workshop',tags:['Free','Outdoor','Family'],desc:'A World Champion freestyler teaches how to make soccer balls dance—playful, visual, and not too precious.',travel:'About 25–35 minutes by transit/cab.',toddler:'A great pre-dinner energy burn if nap ran late.',url:'https://lincolncenter.org/series/summer-for-the-city/sab-family-friendly-ballet-workshop-525'},
 {day:'sat',time:'7:30 PM',end:'Late',title:'AfriCarnaval',place:'Lincoln Center Dance Floor',addr:'Lincoln Center, New York, NY',type:'Music',tags:['Free','Outdoor','All ages'],desc:'Outdoor music and dance celebrating the Caribbean Cultural Center African Diaspora Institute.',travel:'About 25–35 minutes by transit/cab.',toddler:'High-energy but late; use as a short dance-party cameo.',url:'https://www.lincolncenter.org/series/summer-for-the-city'},
 {day:'sun',time:'12:00 PM',end:'5:00 PM',title:'Carnaval Cubano Parade',place:'Madison Ave · 38th to 27th',addr:'Madison Avenue and East 27th Street, New York, NY',type:'Parade',tags:['Free','Outdoor','Closest'],desc:'A lively parade route close to Union Square; watch near the south end for the shortest walk home.',travel:'About 10–15 minutes on foot.',toddler:'Bring hearing protection and bail before crowd fatigue.',url:'https://www.nyc.gov/html/dot/html/motorist/wkndtraf.shtml'},
 {day:'sun',time:'1:00 PM',end:'4:00 PM',title:'Making Moves: Community Art Party',place:'High Line 14th Street Passage',addr:'High Line 14th Street Passage, New York, NY',type:'Art + dance',tags:['Free','Outdoor','Best for kids'],desc:'A kid-highlighted community art and dance party during West Side Fest.',travel:'About 20–30 minutes by transit/cab.',toddler:'Sunday’s strongest child-focused event; pair with snacks in Chelsea Market.',url:'https://www.nycgovparks.org/parks/the-high-line/events/2026/07/12/making-moves-community-art-party-at-west-side-fest'},
 {day:'sun',time:'3:00 PM',end:'6:00 PM',title:'Summer Goals Open Streets + Jazz',place:'Meatpacking District',addr:'Little West 12th Street and West 13th Street, New York, NY',type:'Jazz + crafts',tags:['Free','Outdoor','Drop-in'],desc:'Sunday Open Streets adds sun-print postcards, clay, sachets, crafts and outdoor jazz.',travel:'About 20–30 minutes by transit/cab.',toddler:'Go after nap for music without a formal seat.',url:'https://meatpacking-district.com/summer-goals-july-12'},
 {day:'sun',time:'4:00 PM',end:'6:00 PM',title:'Very Hungry Caterpillar Show',place:'DR2 Theatre',addr:'DR2 Theatre, New York, NY',type:'Classic theater',classic:true,tags:['Ticketed','Indoor backup','Classic'],desc:'A classic picture-book stage option near Union Square; use it for rain, heat or a calmer reset.',travel:'About 5–10 minutes from Union Square.',toddler:'Best seated option, but confirm ticket availability and stroller rules.',url:'https://www.ticketmaster.com/discover/new-york-city?categoryId=family'}
];
const dayMeta={fri:['Friday · July 10','After 5:30 PM'],sat:['Saturday · July 11','10 AM–8 PM window'],sun:['Sunday · July 12','10 AM–8 PM window']};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=a=>'https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',origin:HOME,destination:a});
function card(e){return `<article class="card ${e.classic?'classic':''}" data-kind="${e.classic?'classic':''}"><div class="time">${esc(e.time)}<small>${esc(e.end)}</small></div><div class="body"><div class="badges">${e.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><h3>${esc(e.title)}</h3><b class="place">${esc(e.place)} · ${esc(e.type)}</b><p>${esc(e.desc)}</p><dl><div><dt>Travel</dt><dd>${esc(e.travel)}</dd></div><div><dt>Rayray</dt><dd>${esc(e.toddler)}</dd></div></dl><div class="actions"><a class="primary" href="${esc(e.url)}" target="_blank" rel="noopener">Official details</a><a href="${esc(route(e.addr))}" target="_blank" rel="noopener">Directions</a></div></div></article>`}
document.getElementById('days').innerHTML=['fri','sat','sun'].map(d=>`<section id="${d}" class="day"><div class="dayhead"><div><p class="kicker">${dayMeta[d][1]}</p><h2>${dayMeta[d][0]}</h2></div><p>${events.filter(e=>e.day===d).length} curated happenings, prioritized for flexible toddler attendance.</p></div><div class="grid">${events.filter(e=>e.day===d).map(card).join('')}</div></section>`).join('');
document.getElementById('mapList').innerHTML=events.map((e,i)=>`<a href="${esc(route(e.addr))}" target="_blank" rel="noopener"><span>${i+1}</span><b>${esc(e.title)}</b><small>${esc(e.place)}</small></a>`).join('');
const buttons=[...document.querySelectorAll('[data-filter]')],sections=[...document.querySelectorAll('.day')];
buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.filter;if(f==='classic'){sections.forEach(s=>s.classList.toggle('hide',!s.querySelector('.classic')));document.querySelectorAll('.card').forEach(c=>c.classList.toggle('dim',!c.classList.contains('classic')));document.getElementById('classicPick').scrollIntoView({behavior:'smooth'});return}document.querySelectorAll('.card').forEach(c=>c.classList.remove('dim'));sections.forEach(s=>s.classList.toggle('hide',f!=='all'&&s.id!==f));if(f!=='all')document.getElementById(f).scrollIntoView({behavior:'smooth'});});
