/* Rayray's Weekend: organizer pages checked September 25, 2026.
   Dates below are explicit published dates, never inferred weekly recurrences. */
(() => {
  'use strict';
  const checked = '2026-09-25';
  const items = [
    {id:'camp',type:'indoor',name:'Bluey’s House at CAMP',area:'Flatiron · CAMP New York City',near:true,tags:['Ages 2+','Book ahead'],why:'A nearby, toddler-friendly big outing without a big journey: pretend play inside Bluey’s house, then meet Bluey and Bingo.',when:'50-minute timed experience; choose an available weekend slot.',cost:'Advertised from $30; check tickets for every member of your group.',travel:'About 5–15 min walking.',caution:'This is a paid experience, not free access to the toy store. A character meet-and-greet may be a lot for a shy toddler.',url:'https://camp.com/new-york-city',map:'CAMP Flatiron New York'},
    {id:'books',type:'indoor',name:'Books of Wonder',area:'42 West 17th Street · Flatiron',near:true,tags:['Quiet reset','Free to browse'],why:'An easy picture-book and board-book stop when you want half an hour out of the apartment, not a whole production.',when:'Daily, 11 a.m.–7 p.m.',cost:'Free to browse; purchases optional.',travel:'About 8–15 min walking.',caution:'A bookstore, not a playroom. Check its events calendar separately; a scheduled storytime is not guaranteed.',url:'https://booksofwonder.com/',map:'42 West 17th Street New York'},
    {id:'14y',type:'indoor',name:'14th Street Y family swim',area:'344 East 14th Street · East Village',near:true,tags:['Family members only','Water play'],why:'An active indoor option close to home, with an adult in the water. The membership restriction matters before making this the rainy-day plan.',when:'Use the family-swim schedule, not the lap-pool or building hours.',cost:'Family swim is for 14Y Family Members only. Lessons are a separate paid registration.',travel:'About 15–20 min walking.',caution:'Swim caps are required for everyone; under-threes and children not yet toilet-trained need a swim diaper. Caregiver lessons cover ages 6–35 months.',url:'https://www.14streety.org/health-fitness/aquatics/',map:'344 East 14th Street New York'},
    {id:'chelsea',type:'indoor',name:'Chelsea Piers Toddler Gym',area:'Pier 62 · entrance facing the Hudson',near:false,tags:['Burn energy','Check session'],why:'A toddler-specific space for crawling, rolling and exploring. A better match for two than a general sports court or older-kid obstacle session.',when:'Book a Toddler Gym open-play session; availability and age rules need checking.',cost:'Check the current session price. General programming does not require a family membership.',travel:'About 25–35 min walking, or 15–25 min by cab.',caution:'The Field House’s long opening hours do not mean toddler open play is available all day. Confirm a weekend session before leaving.',url:'https://www.chelseapiers.com/fieldhouse-chelsea',map:'Chelsea Piers Field House Manhattan'},
    {id:'whitney',type:'indoor',name:'A short Whitney visit',area:'99 Gansevoort Street · Meatpacking',near:false,tags:['Stroller-friendly','Art with a toddler'],why:'For a grown-up art outing with Rayray along: choose a short gallery circuit rather than expecting a two-year-old to do a full museum visit.',when:'Friday 10:30 a.m.–10 p.m.; Saturday/Sunday 10:30 a.m.–6 p.m.',cost:'Age 25 and under free; adults $30 normally. Free Friday nights and second Sundays; ground floor always free.',travel:'About 25–35 min walking, or 20–30 min by transit.',caution:'Strollers are permitted throughout. This is a look-not-touch outing, not a toddler play museum. Book admission ahead and check free-entry details.',url:'https://whitney.org/visit',map:'Whitney Museum of American Art New York'},
    {id:'transit',type:'indoor',name:'New York Transit Museum',area:'99 Schermerhorn Street · Downtown Brooklyn',near:false,tags:['Trains','Book ahead'],why:'Vintage subway cars to explore in a real former station. My pick for a vehicle-obsessed toddler who would rather climb aboard than look at a display case.',when:'Wednesday–Sunday, 10 a.m.–4 p.m.',cost:'Paid admission; check current child and adult tickets.',travel:'About 30–45 min by subway.',caution:'The museum currently warns of an air-conditioning outage. The main entrance has stairs; check accessible-entry and stroller arrangements before going.',url:'https://www.nytransitmuseum.org/know-before-you-visit/',map:'New York Transit Museum 99 Schermerhorn Street Brooklyn'},
    {id:'cmom',type:'indoor',name:'CMOM · PlayWorks',area:'212 West 83rd Street · Upper West Side',near:false,tags:['Ages 0–4 area','Strong toddler fit'],why:'A children’s museum with a dedicated under-five play area: a stronger choice for hands-on exploring than an adult museum.',when:'Tuesday–Sunday, 10 a.m.–5 p.m.',cost:'Online: $17 per adult and child age 1–18; in person $18. Under-one babies free.',travel:'About 35–45 min by subway.',caution:'Strollers must be checked, not taken into exhibits. Plan a snack outside; ask for the re-entry sticker before leaving.',url:'https://cmom.org/plan-your-visit/',map:'212 West 83rd Street New York'},
    {id:'amnh',type:'indoor',name:'Natural History, toddler edition',area:'200 Central Park West · Upper West Side',near:false,tags:['Animals + dinosaurs','NY-resident pricing'],why:'Pick one or two halls, not the entire building. Animals, dinosaurs or the blue whale can make a satisfying short visit without following a formal program.',when:'Daily, 10 a.m.–5:30 p.m.; check holiday and gallery closures.',cost:'NY residents with ID can pay what they wish for General Admission. Special exhibitions cost extra.',travel:'About 35–45 min by subway.',caution:'Check which halls are open. For an accessible entrance, use the museum’s Gilder Center or 81st Street entrance information.',url:'https://www.amnh.org/plan-your-visit',map:'American Museum of Natural History New York'},
    {id:'usp',type:'indoor',name:'Union Square Play · Upper East Side',area:'245 East 84th Street · Upper East Side',near:false,tags:['Saturday morning','Not near Union Square'],why:'Child-led play and early-childhood programming. Despite its name, the location listed here is uptown, not by Union Square.',when:'The location lists Saturday 9 a.m.–noon. Check the actual open-play/class booking calendar.',cost:'Session prices and booking requirements vary.',travel:'About 35–45 min by subway.',caution:'Sunday hours were not listed on the location page. Do not assume a class or drop-in is available just because the venue is open.',url:'https://www.unionsquareplay.com/upper-east-side',map:'245 East 84th Street New York'},
    {id:'playstreet',type:'indoor',name:'Play Street Museum · Upper West Side',area:'805 Columbus Avenue · Upper West Side',near:false,tags:['Pretend town','Limited weekend slots'],why:'A small pretend town with role-play spaces, toys and a train table. A good fit for a toddler who likes acting out ordinary grown-up activities.',when:'Weekend play is limited; the site lists a 9–10:30 a.m. session, subject to booking availability.',cost:'$35 per child age 1–8, plus $10 per adult.',travel:'About 40–50 min by subway.',caution:'Reserve before traveling. Socks, caregiver supervision and a waiver are required; no food in the play space.',url:'https://www.uws.playstreetmuseum.com/',map:'805 Columbus Avenue New York'},
    {id:'bcm',type:'indoor',name:'Brooklyn Children’s Museum · Totally Tots',area:'145 Brooklyn Avenue · Crown Heights',near:false,tags:['Ages 0–6','Longer outing'],why:'Sensory play with water, sand, music, dress-up and blocks. Worth considering when the outing itself is the main event, rather than a quick nearby backup.',when:'Wednesday–Sunday, 10 a.m.–5 p.m.',cost:'Paid admission; check the museum’s ticket page.',travel:'About 45–60+ min by subway; beyond the usual easy radius.',caution:'Allow for the journey around nap time. A spare set of clothes is a useful idea for water play.',url:'https://www.brooklynkids.org/exhibits/totally-tots/',map:'145 Brooklyn Avenue Brooklyn'},
    {id:'brotherhood',type:'shabbat',name:'Brotherhood · Tot Shabbat',area:'28 Gramercy Park South · Gramercy',near:true,tags:['Ages 5 and under','Short Friday service'],why:'My first nearby Friday choice for Rayray: a half-hour musical service designed for young children and their families.',when:'Selected Fridays, 5:30–6 p.m. Published fall dates: Oct 2, Oct 16, Nov 6, Nov 13, Dec 11 and Dec 18, 2026.',cost:'Guest-entry, RSVP and any fee requirements need confirmation.',travel:'About 5–10 min walking.',caution:'Not every Friday. Its separate Saturday “Shabbat Corner” is for ages 3–6, so it is not the first choice for a two-year-old.',url:'https://www.brotherhoodsynagogue.org/services-schedule.html',map:'28 Gramercy Park South New York'},
    {id:'townvillage',type:'shabbat',name:'Town & Village · Shabbat B’yaḥad',area:'334 East 14th Street · East Village',near:true,tags:['Young children','Saturday service'],why:'Songs, stories and activities for families with young children, with kiddush, snacks and time together afterward.',when:'The current calendar lists Saturday Sep 26, 2026 at 11 a.m., and Oct 3 at 11 a.m. Check subsequent dates.',cost:'Ask about guest entry and whether advance registration is needed.',travel:'About 15–20 min walking.',caution:'Holiday and long-weekend exceptions apply. Sukkah meals are separate, potentially outdoor events—not an indoor-service guarantee.',url:'https://www.tandv.org/calendar',more:'https://www.tandv.org/earlychildhood',map:'Town and Village Synagogue 334 East 14th Street New York'},
    {id:'eettot',type:'shabbat',name:'East End Temple · Tot Shabbat',area:'245 East 17th Street · Gramercy',near:true,tags:['Birth–5','Confirm next date'],why:'A little-kid musical singalong with dancing and stories, followed by candles, challah and juice. Another very convenient community to try.',when:'The program is described on the service page, but a next Tot Shabbat date/time was not verified.',cost:'Confirm guest entry, registration and any fee with the temple.',travel:'About 8–15 min walking.',caution:'Do not mistake the regular 6:15 p.m. Friday service for Tot Shabbat. Use the calendar or contact the office for the next toddler session.',url:'https://eastendtemple.org/shabbat-services/',more:'https://eastendtemple.org/calendar/',map:'245 East 17th Street New York'},
    {id:'eetfamily',type:'shabbat',name:'East End Temple · all-ages Shabbat & holidays',area:'245 East 17th Street · Gramercy',near:true,tags:['All ages, not tot-only','Festival option'],why:'For a more communal evening with children and adults together. The October 2 celebration includes dancing with the Torah scrolls.',when:'Friday Oct 2, 2026: snacks at 5:45 p.m.; Shabbat/Simchat Torah service and dancing 6:15–7:30 p.m.',cost:'Check the event’s guest/RSVP arrangements.',travel:'About 8–15 min walking.',caution:'This is longer and less toddler-specific than Tot Shabbat. Leave early if Rayray has had enough; do not treat the whole evening as a required commitment.',url:'https://eastendtemple.org/calendar/',map:'245 East 17th Street New York'},
    {id:'cbst',type:'shabbat',name:'CBST · Rainbow Tot Shabbat',area:'130 West 30th Street · Chelsea',near:false,tags:['Ages 0–5','LGBTQ-inclusive'],why:'A welcoming musical and creative morning for little kids and their grown-ups, open to families of all sexual orientations and gender identities.',when:'Published 2026 dates: Oct 10, Nov 14, Dec 12. Creative activity 10:15 a.m.; musical Tot Shabbat 11:30 a.m.; community lunch 12:30 p.m.',cost:'The page invites drop-ins; check guest-entry and any fee details. An interest form provides updates.',travel:'About 25–30 min walking, or 15–25 min by transit.',caution:'You can attend part of the morning; it is not a requirement to stay through lunch. This is monthly, not every Saturday.',url:'https://cbst.org/learning/children/tot-shabbat/',map:'130 West 30th Street New York'},
    {id:'jcp',type:'shabbat',name:'JCP Downtown · Tot Shabbat',area:'146 Duane Street · Tribeca',near:false,tags:['Ages 5 and under','Free · register children'],why:'Singing, dancing, stories and prayer, followed by grape juice and challah. A clear under-five option for a Saturday morning downtown.',when:'Saturday Oct 24, 2026, 10–11 a.m. The calendar also lists Nov 14 and Dec 5 at 10 a.m.',cost:'Oct 24 is free. Register each child; accompanying adults do not need a separate registration.',travel:'About 20–30 min by subway.',caution:'Registration was marked “coming soon” when checked. A published event is not proof that places are currently bookable.',url:'https://jcpdowntown.org/events/tot-shabbat-10/',more:'https://jcpdowntown.org/events/category/cal-early-childhood/',map:'146 Duane Street New York'}
  ];
  const dates = [
    ['2026-09-26','11 a.m.','townvillage'],
    ['2026-10-02','5:30–6 p.m.','brotherhood'],
    ['2026-10-02','5:45 p.m. snacks','eetfamily'],
    ['2026-10-03','11 a.m.','townvillage'],
    ['2026-10-10','10:15 a.m. / 11:30 a.m.','cbst'],
    ['2026-10-16','5:30–6 p.m.','brotherhood'],
    ['2026-10-24','10–11 a.m.','jcp'],
    ['2026-11-06','5:30–6 p.m.','brotherhood'],
    ['2026-11-13','5:30–6 p.m.','brotherhood'],
    ['2026-11-14','10:15 a.m. / 11:30 a.m.','cbst'],
    ['2026-11-14','10–11 a.m.','jcp'],
    ['2026-12-05','10–11 a.m.','jcp'],
    ['2026-12-11','5:30–6 p.m.','brotherhood'],
    ['2026-12-12','10:15 a.m. / 11:30 a.m.','cbst'],
    ['2026-12-18','5:30–6 p.m.','brotherhood']
  ];
  const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const byId = id => items.find(item => item.id === id);
  const today = new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const formatDate = date => new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(date+'T12:00:00-04:00'));
  const map = value => 'https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',origin:'Union Square, Manhattan, New York',destination:value});
  let saved = new Set();
  try { const stored = JSON.parse(localStorage.getItem('rayray-weekend-saved') || '[]'); if(Array.isArray(stored)) saved = new Set(stored.filter(id => byId(id))); } catch (_) { /* Private browsing can disable storage. */ }
  let category = 'all';
  const grid = document.getElementById('guide-cards');
  const search = document.getElementById('guide-search');
  const nearby = document.getElementById('nearby-only');
  const savedOnly = document.getElementById('saved-only');
  const result = document.getElementById('result-count');
  function card(item) {
    const isSaved = saved.has(item.id);
    return `<article class="guide-card ${item.type}" id="activity-${item.id}"><div class="card-top"><span class="eyebrow">${item.type==='indoor'?'INDOOR':'SHABBAT + FAMILY'}</span><button class="save" type="button" data-save="${item.id}" aria-pressed="${isSaved}" aria-label="${isSaved?'Unsave':'Save'} ${escape(item.name)}">${isSaved?'★ Saved':'☆ Save'}</button></div><h3>${escape(item.name)}</h3><p class="guide-place">${escape(item.area)}</p><div class="badges">${item.tags.map(t=>`<span>${escape(t)}</span>`).join('')}${item.near?'<span>Easy walk</span>':''}</div><p class="why">${escape(item.why)}</p><dl class="facts"><div><dt>When</dt><dd>${escape(item.when)}</dd></div><div><dt>Cost / access</dt><dd>${escape(item.cost)}</dd></div><div><dt>Travel estimate</dt><dd>${escape(item.travel)}</dd></div></dl><p class="caution"><strong>Before going:</strong> ${escape(item.caution)}</p><div class="actions"><a class="primary" target="_blank" rel="noopener noreferrer" href="${escape(item.url)}">Official details ↗</a>${item.more?`<a target="_blank" rel="noopener noreferrer" href="${escape(item.more)}">Program / calendar ↗</a>`:''}<a target="_blank" rel="noopener noreferrer" href="${escape(map(item.map))}">Directions ↗</a></div></article>`;
  }
  function render() {
    const q = search.value.trim().toLocaleLowerCase();
    const filtered = items.filter(item => (category==='all'||item.type===category)&&(!nearby.checked||item.near)&&(!savedOnly.checked||saved.has(item.id))&&(!q||[item.name,item.area,item.why,...item.tags].join(' ').toLocaleLowerCase().includes(q)));
    grid.innerHTML = filtered.map(card).join('');
    result.textContent = `${filtered.length} of ${items.length} options${category==='shabbat'?' · Programs are not automatically weekly.':''}`;
    document.getElementById('no-results').hidden = filtered.length>0;
    document.querySelectorAll('[data-category]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.category===category)));
  }
  function setCategory(value) { category=value; render(); }
  document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>setCategory(button.dataset.category)));
  [search,nearby,savedOnly].forEach(control=>control.addEventListener(control===search?'input':'change',render));
  grid.addEventListener('click',event=>{
    const button=event.target.closest('[data-save]'); if(!button)return;
    const id=button.dataset.save; saved.has(id)?saved.delete(id):saved.add(id);
    try{localStorage.setItem('rayray-weekend-saved',JSON.stringify([...saved]));}catch(_){document.getElementById('storage-note').hidden=false;}
    render();
    const replacement=grid.querySelector(`[data-save="${id}"]`); if(replacement)replacement.focus();
  });
  document.getElementById('clear-filters').addEventListener('click',()=>{search.value='';nearby.checked=false;savedOnly.checked=false;setCategory('all');});
  document.querySelectorAll('[data-jump]').forEach(link=>link.addEventListener('click',()=>{search.value='';nearby.checked=false;savedOnly.checked=false;setCategory(link.dataset.jump);}));
  document.getElementById('upcoming').innerHTML=dates.filter(date=>date[0]>=today).slice(0,6).map(([date,time,id])=>{const item=byId(id);return `<a class="date-card" href="#activity-${id}" data-activity="${id}"><time datetime="${date}">${escape(formatDate(date))}</time><strong>${escape(item.name)}</strong><span>${escape(time)}</span></a>`;}).join('')||'<p>No future dates remain in this checked list. Open the organizer calendars below; this page does not automatically fetch new events.</p>';
  document.getElementById('upcoming').addEventListener('click',event=>{const link=event.target.closest('[data-activity]');if(!link)return;search.value='';nearby.checked=false;savedOnly.checked=false;setCategory('shabbat');});
  if(today>'2026-10-25')document.getElementById('stale-note').hidden=false;
  const target=location.hash.replace('#activity-','');
  if(location.hash.startsWith('#activity-')&&byId(target))category=byId(target).type;
  render();
  if(location.hash.startsWith('#activity-'))document.getElementById(location.hash.slice(1))?.scrollIntoView();
  document.getElementById('print-guide').addEventListener('click',()=>window.print());
  document.documentElement.dataset.guideChecked=checked;
})();
